version: '3.8'

services:
  emulator:
    image: budtmo/docker-android-x86-11.0
    privileged: true
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEVICE=${DEVICE_NAME:-Samsung Galaxy S10}
      - EMULATOR_ARGS=-no-window -gpu swiftshader_indirect
      - APPIUM=false

  appium:
    image: appium/appium:2.5.4
    depends_on:
      - emulator
    network_mode: "service:emulator"
    command: ["appium", "--base-path", "/wd/hub", "-p", "4723"]

  tests:
    build: .
    depends_on:
      - emulator
      - appium
    volumes:
      - ./allure-results:/app/allure-results
      - ./target/surefire-reports:/app/target/surefire-reports
    environment:
      - APPIUM_SERVER=${APPIUM_SERVER:-http://appium:4723/wd/hub}
      - DEVICE_NAME=${DEVICE_NAME:-emulator-5554}
      - APP_PATH=${APP_PATH}
