services:
  appium:
    image: appium/appium:2.5.4
    ports:
      - "4723:4723"
    command: ["appium", "--base-path", "/wd/hub", "-p", "4723"]

  tests:
    build: .
    depends_on:
      - appium
    volumes:
      - ./allure-results:/app/allure-results
      - ./target/surefire-reports:/app/target/surefire-reports
    environment:
      - APPIUM_SERVER=${APPIUM_SERVER:-http://127.0.0.1:4723/wd/hub}
      - DEVICE_NAME=${DEVICE_NAME:-emulator-5554}
      - APP_PATH=${APP_PATH}
