name: Run Android Appium Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: appium_swaglabs_automation
  APPIUM_SERVER: http://appium:4723/wd/hub
  DEVICE_NAME: emulator-5554
  APP_PATH: ./src/test/resources/apps/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Start emulator, install APK, and run tests
        run: |
          mkdir -p allure-results target/surefire-reports
          chmod 777 allure-results target/surefire-reports

          echo ">>> Starting emulator and Appium..."
          docker compose up -d emulator appium

          echo ">>> Waiting for emulator device..."
          until adb devices | grep emulator-5554; do
            echo "Waiting for emulator device..."
            sleep 5
          done

          echo ">>> Waiting for emulator to fully boot..."
          boot_completed=""
          while [ "$boot_completed" != "1" ]; do
            boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Emulator boot status: $boot_completed"
            sleep 5
          done
          echo "Emulator fully booted!"

          echo ">>> Installing APK on emulator..."
          adb -s emulator-5554 install -r $APP_PATH

          echo ">>> Running tests..."
          docker compose up --abort-on-container-exit tests

      - name: Upload Allure results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload JUnit reports as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports

  deploy-allure-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages

  notify-slack:
    needs: [ test, deploy-allure-report ]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send Slack notification
        run: |
          STATUS="${{ needs.test.result }}"
          EMOJI="❌"
          if [ "$STATUS" = "success" ]; then
            EMOJI="✅"
          fi
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"${EMOJI} Android Appium CI/CD finished with status: *$STATUS*\nRepo: $GITHUB_REPOSITORY\nCommit: <https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|$GITHUB_SHA>\nAllure Report: https://$GITHUB_REPOSITORY.github.io/allure-report\" 
          }" ${{ secrets.SLACK_WEBHOOK_URL }}