name: Run Android Appium Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APPIUM_SERVER: http://appium:4723/wd/hub
  DEVICE_NAME: emulator-5554
  APP_PATH: ./src/test/resources/apps/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      IMAGE_NAME: appium_swaglabs_automation
      APPIUM_SERVER: ${{ env.APPIUM_SERVER }}
      DEVICE_NAME: ${{ env.DEVICE_NAME }}
      APP_PATH: ${{ env.APP_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Start emulator, Appium, and run tests
        run: |
          mkdir -p allure-results target/surefire-reports
          chmod 777 allure-results target/surefire-reports
          docker compose up --abort-on-container-exit --build
        env:
          APPIUM_SERVER: ${{ env.APPIUM_SERVER }}
          DEVICE_NAME: ${{ env.DEVICE_NAME }}
          APP_PATH: ${{ env.APP_PATH }}

      - name: Upload Allure results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload JUnit reports as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports

  deploy-allure-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages

  notify-slack:
    needs: [ test, deploy-allure-report ]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send Slack notification
        run: |
          STATUS="${{ needs.test.result }}"
          EMOJI="❌"
          if [ "$STATUS" = "success" ]; then
            EMOJI="✅"
          fi
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"${EMOJI} Android Appium CI/CD finished with status: *$STATUS*\nRepo: $GITHUB_REPOSITORY\nCommit: <https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|$GITHUB_SHA>\nAllure Report: https://$GITHUB_REPOSITORY.github.io/allure-report\"\n
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
